coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 10%
    patch:
      default:
        target: 90%
        threshold: 10%

ignore:
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/__tests__/**"
  - "**/__mocks__/**"
