coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 10%
    patch:
      default:
        target: 90%
        threshold: 10%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true

ignore:
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/__tests__/**"
  - "**/__mocks__/**"
